### ISSUE TITLE
Epic games version

### ISSUE THREAD

**Issue by Outofit08** [AGameAnx/dok-ge-mod#2]
Hi there are hard-coded settings that force the app to launch steam. But People with the epic game version only will not be able to run this mod.

**Comment by AGameAnx** [comment]
EGS version had steam functionality cut out from its dlls, whereas it is normal for steam games to launch steam when they're launched. I'm presuming that the functionality you're describing would happen if steam version files of the mod would be used with EGS version. 1.3 mod version files were not functional with 1.4 version of the game at all anyway.

I've now released a new 1.4 version of the mod and it features two different archives for Steam and EGS and should work appropriately.
